spring:
  application:
    name: patient-service

  data:
    mongodb:
      uri: ${MONGODB_URI}

  main:
    allow-circular-references: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

server:
  port: 8081

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
