spring:
  application:
    name: patient-service

  spring:
    data:
      mongodb:
        uri: mongodb+srv://nayeebhautik:mwhCiZQrsLv2NnWh@cluster0.8z3mt.mongodb.net/healthtrack?retryWrites=true&w=majority&appName=Cluster0

  main:
    allow-circular-references: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

server:
  port: 8081

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
