spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patient-service/**
          filters:
            - StripPrefix=1

        - id: vitals-service
          uri: http://localhost:8082
          predicates:
            - Path=/vitals-service/**
          filters:
            - StripPrefix=1

        - id: alert-service
          uri: http://localhost:8083
          predicates:
            - Path=/alert-service/**
          filters:
            - StripPrefix=1
